<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Week 1 | Intro to data and Probability</title>
  <meta name="description" content="This is my course activity for the Introduction to Probability and Data offered by Duke University on Coursera">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Week 1 | Intro to data and Probability" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is my course activity for the Introduction to Probability and Data offered by Duke University on Coursera" />
  <meta name="github-repo" content="akshaykumarreddy/intro-data-prob" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Week 1 | Intro to data and Probability" />
  
  <meta name="twitter:description" content="This is my course activity for the Introduction to Probability and Data offered by Duke University on Coursera" />
  

<meta name="author" content="Akshay Kotha">


<meta name="date" content="2018-12-30">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="index.html">
<link rel="next" href="week-2.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Intro to data and Probability</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a></li>
<li class="chapter" data-level="" data-path="week-1.html"><a href="week-1.html"><i class="fa fa-check"></i>Week 1</a><ul>
<li class="chapter" data-level="0.1" data-path="week-1.html"><a href="week-1.html#introduction-to-r-and-rstudio"><i class="fa fa-check"></i><b>0.1</b> ## Introduction to R and RStudio</a></li>
<li class="chapter" data-level="0.2" data-path="week-1.html"><a href="week-1.html#rstudio"><i class="fa fa-check"></i><b>0.2</b> RStudio</a></li>
<li class="chapter" data-level="0.3" data-path="week-1.html"><a href="week-1.html#r-packages"><i class="fa fa-check"></i><b>0.3</b> R Packages</a></li>
<li class="chapter" data-level="0.4" data-path="week-1.html"><a href="week-1.html#dataset-1-dr.arbuthnots-baptism-records"><i class="fa fa-check"></i><b>0.4</b> Dataset 1: Dr. Arbuthnot’s Baptism Records</a><ul>
<li class="chapter" data-level="0.4.1" data-path="week-1.html"><a href="week-1.html#r-markdown"><i class="fa fa-check"></i><b>0.4.1</b> R Markdown</a></li>
<li class="chapter" data-level="0.4.2" data-path="week-1.html"><a href="week-1.html#some-exploration"><i class="fa fa-check"></i><b>0.4.2</b> Some Exploration</a></li>
<li class="chapter" data-level="0.4.3" data-path="week-1.html"><a href="week-1.html#r-as-a-big-calculator"><i class="fa fa-check"></i><b>0.4.3</b> R as a big calculator</a></li>
<li class="chapter" data-level="0.4.4" data-path="week-1.html"><a href="week-1.html#adding-a-new-variable-to-the-data-frame"><i class="fa fa-check"></i><b>0.4.4</b> Adding a new variable to the data frame</a></li>
</ul></li>
<li class="chapter" data-level="0.5" data-path="week-1.html"><a href="week-1.html#dataset-2-present-birth-records"><i class="fa fa-check"></i><b>0.5</b> Dataset 2: Present birth records</a></li>
<li class="chapter" data-level="0.6" data-path="week-1.html"><a href="week-1.html#resources-for-learning-r-and-working-in-rstudio"><i class="fa fa-check"></i><b>0.6</b> Resources for learning R and working in RStudio</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="week-2.html"><a href="week-2.html"><i class="fa fa-check"></i>Week 2</a><ul>
<li class="chapter" data-level="0.7" data-path="week-2.html"><a href="week-2.html#getting-started"><i class="fa fa-check"></i><b>0.7</b> Getting started</a><ul>
<li class="chapter" data-level="0.7.1" data-path="week-2.html"><a href="week-2.html#load-packages"><i class="fa fa-check"></i><b>0.7.1</b> Load packages</a></li>
<li class="chapter" data-level="0.7.2" data-path="week-2.html"><a href="week-2.html#data"><i class="fa fa-check"></i><b>0.7.2</b> Data</a></li>
<li class="chapter" data-level="0.7.3" data-path="week-2.html"><a href="week-2.html#seven-verbs"><i class="fa fa-check"></i><b>0.7.3</b> Seven verbs</a></li>
</ul></li>
<li class="chapter" data-level="0.8" data-path="week-2.html"><a href="week-2.html#analysis"><i class="fa fa-check"></i><b>0.8</b> Analysis</a><ul>
<li class="chapter" data-level="0.8.1" data-path="week-2.html"><a href="week-2.html#departure-delays-in-flights-to-raleigh-durham-rdu"><i class="fa fa-check"></i><b>0.8.1</b> Departure delays in flights to Raleigh-Durham (RDU)</a></li>
<li class="chapter" data-level="0.8.2" data-path="week-2.html"><a href="week-2.html#departure-delays-over-months"><i class="fa fa-check"></i><b>0.8.2</b> Departure delays over months</a></li>
<li class="chapter" data-level="0.8.3" data-path="week-2.html"><a href="week-2.html#on-time-departure-rate-for-nyc-airports"><i class="fa fa-check"></i><b>0.8.3</b> On time departure rate for NYC airports</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="week-3.html"><a href="week-3.html"><i class="fa fa-check"></i>Week 3</a><ul>
<li class="chapter" data-level="0.9" data-path="week-3.html"><a href="week-3.html#hot-hands"><i class="fa fa-check"></i><b>0.9</b> Hot Hands</a></li>
<li class="chapter" data-level="0.10" data-path="week-3.html"><a href="week-3.html#getting-started-1"><i class="fa fa-check"></i><b>0.10</b> Getting Started</a><ul>
<li class="chapter" data-level="0.10.1" data-path="week-3.html"><a href="week-3.html#load-packages-1"><i class="fa fa-check"></i><b>0.10.1</b> Load packages</a></li>
<li class="chapter" data-level="0.10.2" data-path="week-3.html"><a href="week-3.html#data-1"><i class="fa fa-check"></i><b>0.10.2</b> Data</a></li>
</ul></li>
<li class="chapter" data-level="0.11" data-path="week-3.html"><a href="week-3.html#compared-to-what"><i class="fa fa-check"></i><b>0.11</b> Compared to What?</a></li>
<li class="chapter" data-level="0.12" data-path="week-3.html"><a href="week-3.html#simulations-in-r"><i class="fa fa-check"></i><b>0.12</b> Simulations in R</a></li>
<li class="chapter" data-level="0.13" data-path="week-3.html"><a href="week-3.html#simulating-the-independent-shooter"><i class="fa fa-check"></i><b>0.13</b> Simulating the Independent Shooter</a><ul>
<li class="chapter" data-level="0.13.1" data-path="week-3.html"><a href="week-3.html#comparing-kobe-bryant-to-the-independent-shooter"><i class="fa fa-check"></i><b>0.13.1</b> Comparing Kobe Bryant to the Independent Shooter</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="week-4.html"><a href="week-4.html"><i class="fa fa-check"></i>Week 4</a><ul>
<li class="chapter" data-level="0.14" data-path="week-4.html"><a href="week-4.html#setup"><i class="fa fa-check"></i><b>0.14</b> Setup</a><ul>
<li class="chapter" data-level="0.14.1" data-path="week-4.html"><a href="week-4.html#load-packages-2"><i class="fa fa-check"></i><b>0.14.1</b> Load packages</a></li>
<li class="chapter" data-level="0.14.2" data-path="week-4.html"><a href="week-4.html#load-data"><i class="fa fa-check"></i><b>0.14.2</b> Load data</a></li>
</ul></li>
<li class="chapter" data-level="0.15" data-path="week-4.html"><a href="week-4.html#part-1-data"><i class="fa fa-check"></i><b>0.15</b> Part 1: Data</a></li>
<li class="chapter" data-level="0.16" data-path="week-4.html"><a href="week-4.html#part-2-research-questions"><i class="fa fa-check"></i><b>0.16</b> Part 2: Research questions</a><ul>
<li class="chapter" data-level="0.16.1" data-path="week-4.html"><a href="week-4.html#research-quesion-1"><i class="fa fa-check"></i><b>0.16.1</b> Research quesion 1:</a></li>
<li class="chapter" data-level="0.16.2" data-path="week-4.html"><a href="week-4.html#research-quesion-2"><i class="fa fa-check"></i><b>0.16.2</b> Research quesion 2:</a></li>
<li class="chapter" data-level="0.16.3" data-path="week-4.html"><a href="week-4.html#research-quesion-3"><i class="fa fa-check"></i><b>0.16.3</b> Research quesion 3:</a></li>
</ul></li>
<li class="chapter" data-level="0.17" data-path="week-4.html"><a href="week-4.html#part-3-exploratory-data-analysis"><i class="fa fa-check"></i><b>0.17</b> Part 3: Exploratory data analysis</a><ul>
<li class="chapter" data-level="0.17.1" data-path="week-4.html"><a href="week-4.html#research-quesion-1-code"><i class="fa fa-check"></i><b>0.17.1</b> Research quesion 1: Code</a></li>
<li class="chapter" data-level="0.17.2" data-path="week-4.html"><a href="week-4.html#narrative-of-question-1"><i class="fa fa-check"></i><b>0.17.2</b> Narrative of question 1:</a></li>
<li class="chapter" data-level="0.17.3" data-path="week-4.html"><a href="week-4.html#research-quesion-2-code"><i class="fa fa-check"></i><b>0.17.3</b> Research quesion 2: Code</a></li>
<li class="chapter" data-level="0.17.4" data-path="week-4.html"><a href="week-4.html#narrative-of-question-2"><i class="fa fa-check"></i><b>0.17.4</b> Narrative of question 2:</a></li>
<li class="chapter" data-level="0.17.5" data-path="week-4.html"><a href="week-4.html#research-quesion-3-code"><i class="fa fa-check"></i><b>0.17.5</b> Research quesion 3: Code</a></li>
<li class="chapter" data-level="0.17.6" data-path="week-4.html"><a href="week-4.html#narrative-question-3"><i class="fa fa-check"></i><b>0.17.6</b> Narrative question 3:</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Intro to data and Probability</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="week-1" class="section level1 unnumbered">
<h1>Week 1</h1>
<div id="introduction-to-r-and-rstudio" class="section level2">
<h2><span class="header-section-number">0.1</span> ## Introduction to R and RStudio</h2>
<p>title: “” output: statsr:::statswithr_lab —</p>
<div id="instructions">
<p>Complete all <strong>Exercises</strong>, and submit answers to <strong>Questions</strong> on the Coursera platform.</p>
</div>
<p>The goal of this lab is to introduce you to R and RStudio, which you’ll be using throughout the course both to learn the statistical concepts discussed in the course and to analyze real data and come to informed conclusions. To straighten out which is which: R is the name of the programming language itself and RStudio is a convenient interface.</p>
<p>As the labs progress, you are encouraged to explore beyond what the labs dictate; a willingness to experiment will make you a much better programmer. Before we get to that stage, however, you need to build some basic fluency in R. Today we begin with the fundamental building blocks of R and RStudio: the interface, reading in data, and basic commands.</p>
</div>
<div id="rstudio" class="section level2">
<h2><span class="header-section-number">0.2</span> RStudio</h2>
<p>Your RStudio window has four panels.</p>
<p>Your R Markdown file (this document) is in the upper left panel.</p>
<p>The panel on the lower left is where the action happens. It’s called the <em>console</em>. Everytime you launch RStudio, it will have the same text at the top of the console telling you the version of R that you’re running. Below that information is the <em>prompt</em>. As its name suggests, this prompt is really a request, a request for a command. Initially, interacting with R is all about typing commands and interpreting the output. These commands and their syntax have evolved over decades (literally) and now provide what many users feel is a fairly natural way to access data and organize, describe, and invoke statistical computations.</p>
<p>The panel in the upper right contains your <em>workspace</em> as well as a history of the commands that you’ve previously entered.</p>
<p>Any plots that you generate will show up in the panel in the lower right corner. This is also where you can browse your files, access help, manage packages, etc.</p>
</div>
<div id="r-packages" class="section level2">
<h2><span class="header-section-number">0.3</span> R Packages</h2>
<p>R is an open-source programming language, meaning that users can contribute packages that make our lives easier, and we can use them for free. For this lab, and many others in the future, we will use the following R packages:</p>
<ul>
<li><code>statsr</code>: for data files and functions used in this course</li>
<li><code>dplyr</code>: for data wrangling</li>
<li><code>ggplot2</code>: for data visualization</li>
</ul>
<p>You should have already installed these packages using commands like <code>install.packages</code> and <code>install_github</code>.</p>
<p>Next, you need to load the packages in your working environment. We do this with the <code>library</code> function. Note that you only need to <strong>install</strong> packages once, but you need to <strong>load</strong> them each time you relaunch RStudio.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dplyr)
<span class="kw">library</span>(ggplot2)
<span class="kw">library</span>(statsr)</code></pre></div>
<p>To do so, you can</p>
<ul>
<li>click on the green arrow at the top of the code chunk in the R Markdown (Rmd) file, or</li>
<li>highlight these lines, and hit the <strong>Run</strong> button on the upper right corner of the pane, or</li>
<li>type the code in the console.</li>
</ul>
<p>Going forward you will be asked to load any relevant packages at the beginning of each lab.</p>
</div>
<div id="dataset-1-dr.arbuthnots-baptism-records" class="section level2">
<h2><span class="header-section-number">0.4</span> Dataset 1: Dr. Arbuthnot’s Baptism Records</h2>
<p>To get you started, run the following command to load the data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(arbuthnot)</code></pre></div>
<p>To do so, once again, you can</p>
<ul>
<li>click on the green arrow at the top of the code chunk in the R Markdown (Rmd) file, or</li>
<li>put your cursor on this line, and hit the <strong>Run</strong> button on the upper right corner of the pane, or</li>
<li>type the code in the console.</li>
</ul>
<p>This command instructs R to load some data. The Arbuthnot baptism counts for boys and girls. You should see that the workspace area in the upper righthand corner of the RStudio window now lists a data set called <code>arbuthnot</code> that has 82 observations on 3 variables. As you interact with R, you will create a series of objects. Sometimes you load them as we have done here, and sometimes you create them yourself as the byproduct of a computation or some analysis you have performed.</p>
<p>The Arbuthnot data set refers to Dr. John Arbuthnot, an 18<sup>th</sup> century physician, writer, and mathematician. He was interested in the ratio of newborn boys to newborn girls, so he gathered the baptism records for children born in London for every year from 1629 to 1710. We can take a look at the data by typing its name into the console.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">arbuthnot</code></pre></div>
<pre><code>## # A tibble: 82 x 3
##     year  boys girls
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;
##  1  1629  5218  4683
##  2  1630  4858  4457
##  3  1631  4422  4102
##  4  1632  4994  4590
##  5  1633  5158  4839
##  6  1634  5035  4820
##  7  1635  5106  4928
##  8  1636  4917  4605
##  9  1637  4703  4457
## 10  1638  5359  4952
## # ... with 72 more rows</code></pre>
<p>However printing the whole dataset in the console is not that useful. One advantage of RStudio is that it comes with a built-in data viewer. Click on the name <code>arbuthnot</code> in the <em>Environment</em> pane (upper right window) that lists the objects in your workspace. This will bring up an alternative display of the data set in the <em>Data Viewer</em> (upper left window). You can close the data viewer by clicking on the <em>x</em> in the upper lefthand corner.</p>
<p>What you should see are four columns of numbers, each row representing a different year: the first entry in each row is simply the row number (an index we can use to access the data from individual years if we want), the second is the year, and the third and fourth are the numbers of boys and girls baptized that year, respectively. Use the scrollbar on the right side of the console window to examine the complete data set.</p>
<p>Note that the row numbers in the first column are not part of Arbuthnot’s data. R adds them as part of its printout to help you make visual comparisons. You can think of them as the index that you see on the left side of a spreadsheet. In fact, the comparison to a spreadsheet will generally be helpful. R has stored Arbuthnot’s data in a kind of spreadsheet or table called a <em>data frame</em>.</p>
<p>You can see the dimensions of this data frame by typing:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(arbuthnot)</code></pre></div>
<pre><code>## [1] 82  3</code></pre>
<p>This command should output <code>[1] 82 3</code>, indicating that there are 82 rows and 3 columns (we’ll get to what the <code>[1]</code> means in a bit), just as it says next to the object in your workspace. You can see the names of these columns (or variables) by typing:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">names</span>(arbuthnot)</code></pre></div>
<pre><code>## [1] &quot;year&quot;  &quot;boys&quot;  &quot;girls&quot;</code></pre>
<ol style="list-style-type: decimal">
<li>How many variables are included in this data set?
<ol>
<li>
2
</li>
<li>
3
</li>
<li>
4
</li>
<li>
82
</li>
<li>
1710
</li>
</ol></li>
</ol>
<div id="exercise">
<p><strong>Exercise</strong>: What years are included in this dataset? Hint: Take a look at the year variable in the Data Viewer to answer this question.</p>
</div>
<p>You should see that the data frame contains the columns <code>year</code>, <code>boys</code>, and <code>girls</code>. At this point, you might notice that many of the commands in R look a lot like functions from math class; that is, invoking R commands means supplying a function with some number of arguments. The <code>dim</code> and <code>names</code> commands, for example, each took a single argument, the name of a data frame.</p>
<div id="boxedtext">
<p><strong>Tip: </strong> If you use the up and down arrow keys, you can scroll through your previous commands, your so-called command history. You can also access it by clicking on the history tab in the upper right panel. This will save you a lot of typing in the future.</p>
</div>
<div id="r-markdown" class="section level3">
<h3><span class="header-section-number">0.4.1</span> R Markdown</h3>
<p>So far we asked you to type your commands in the console. The console is a great place for playing around with some code, however it is not a good place for documenting your work. Working in the console exclusively makes it difficult to document your work as you go, and reproduce it later.</p>
<p>R Markdown is a great solution for this problem. And, you already have worked with an R Markdown document – this lab! Going forward type the code for the questions in the code chunks provided in the R Markdown (Rmd) document for the lab, and <strong>Knit</strong> the document to see the results.</p>
</div>
<div id="some-exploration" class="section level3">
<h3><span class="header-section-number">0.4.2</span> Some Exploration</h3>
<p>Let’s start to examine the data a little more closely. We can access the data in a single column of a data frame separately using a command like</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">arbuthnot<span class="op">$</span>boys</code></pre></div>
<pre><code>##  [1] 5218 4858 4422 4994 5158 5035 5106 4917 4703 5359 5366 5518 5470 5460
## [15] 4793 4107 4047 3768 3796 3363 3079 2890 3231 3220 3196 3441 3655 3668
## [29] 3396 3157 3209 3724 4748 5216 5411 6041 5114 4678 5616 6073 6506 6278
## [43] 6449 6443 6073 6113 6058 6552 6423 6568 6247 6548 6822 6909 7577 7575
## [57] 7484 7575 7737 7487 7604 7909 7662 7602 7676 6985 7263 7632 8062 8426
## [71] 7911 7578 8102 8031 7765 6113 8366 7952 8379 8239 7840 7640</code></pre>
<p>This command will only show the number of boys baptized each year. The dollar sign basically says “go to the data frame that comes before me, and find the variable that comes after me”.</p>
<ol start="2" style="list-style-type: decimal">
<li>What command would you use to extract just the counts of girls born?
<ol>
<li>
<code>arbuthnot$boys</code>
</li>
<li>
<code>arbuthnot$girls</code>
</li>
<li>
<code>girls</code>
</li>
<li>
<code>arbuthnot[girls]</code>
</li>
<li>
<code>$girls</code>
</li>
</ol></li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># type your code for the Question 2 here, and Knit</span>
arbuthnot<span class="op">$</span>girls</code></pre></div>
<pre><code>##  [1] 4683 4457 4102 4590 4839 4820 4928 4605 4457 4952 4784 5332 5200 4910
## [15] 4617 3997 3919 3395 3536 3181 2746 2722 2840 2908 2959 3179 3349 3382
## [29] 3289 3013 2781 3247 4107 4803 4881 5681 4858 4319 5322 5560 5829 5719
## [43] 6061 6120 5822 5738 5717 5847 6203 6033 6041 6299 6533 6744 7158 7127
## [57] 7246 7119 7214 7101 7167 7302 7392 7316 7483 6647 6713 7229 7767 7626
## [71] 7452 7061 7514 7656 7683 5738 7779 7417 7687 7623 7380 7288</code></pre>
<p>Notice that the way R has printed these data is different. When we looked at the complete data frame, we saw 82 rows, one on each line of the display. These data are no longer structured in a table with other variables, so they are displayed one right after another. Objects that print out in this way are called vectors; they represent a set of numbers. R has added numbers in [brackets] along the left side of the printout to indicate locations within the vector. For example, in the arbuthnot$boys vector, 5218 follows [1], indicating that 5218 is the first entry in the vector. And if [43] starts a line, then that would mean the first number on that line would represent the 43rd entry in the vector.</p>
<p>R has some powerful functions for making graphics. We can create a simple plot of the number of girls baptized per year with the command</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> arbuthnot, <span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> girls)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>()</code></pre></div>
<p><img src="intro-to-data-prob_files/figure-html/plot-girls-vs-year-1.png" width="672" /></p>
<p>Before we review the code for this plot, let’s summarize the trends we see in the data.</p>
<ol style="list-style-type: decimal">
<li>Which of the following best describes the number of girls baptised over the years included in this dataset?
<ol>
<li>
There appears to be no trend in the number of girls baptised from 1629 to 1710.
</li>
<li>
There is initially an increase in the number of girls baptised, which peaks around 1640. After 1640 there is a decrease in the number of girls baptised, but the number begins to increase again in 1660. Overall the trend is an increase in the number of girls baptised.
</li>
<li>
There is initially an increase in the number of girls baptised. This number peaks around 1640 and then after 1640 the number of girls baptised decreases.
</li>
<li>
The number of girls baptised has decreased over time.
</li>
<li>
There is an initial increase in the number of girls baptised but this number appears to level around 1680 and not change after that time point.
</li>
</ol></li>
</ol>
<p>Back to the code… We use the <code>ggplot()</code> function to build plots. If you run the plotting code in your console, you should see the plot appear under the <em>Plots</em> tab of the lower right panel of RStudio. Notice that the command above again looks like a function, this time with arguments separated by commas.</p>
<ul>
<li>The first argument is always the dataset.</li>
<li>Next, we provide thevariables from the dataset to be assigned to <code>aes</code>thetic elements of the plot, e.g. the x and the y axes.</li>
<li>Finally, we use another layer, separated by a <code>+</code> to specify the <code>geom</code>etric object for the plot. Since we want to scatterplot, we use <code>geom_point</code>.</li>
</ul>
<p>You might wonder how you are supposed to know the syntax for the <code>ggplot</code> function. Thankfully, R documents all of its functions extensively. To read what a function does and learn the arguments that are available to you, just type in a question mark followed by the name of the function that you’re interested in. Try the following in your console:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#?ggplot</span></code></pre></div>
<p>Notice that the help file replaces the plot in the lower right panel. You can toggle between plots and help files using the tabs at the top of that panel.</p>
<div id="boxedtext">
<p>More extensive help for plotting with the <code>ggplot2</code> package can be found at <a href="http://docs.ggplot2.org/current/" class="uri">http://docs.ggplot2.org/current/</a>. The best (and easiest) way to learn the syntax is to take a look at the sample plots provided on that page, and modify the code bit by bit until you get achieve the plot you want.</p>
</div>
</div>
<div id="r-as-a-big-calculator" class="section level3">
<h3><span class="header-section-number">0.4.3</span> R as a big calculator</h3>
<p>Now, suppose we want to plot the total number of baptisms. To compute this, we could use the fact that R is really just a big calculator. We can type in mathematical expressions like</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">5218</span> <span class="op">+</span><span class="st"> </span><span class="dv">4683</span></code></pre></div>
<pre><code>## [1] 9901</code></pre>
<p>to see the total number of baptisms in 1629. We could repeat this once for each year, but there is a faster way. If we add the vector for baptisms for boys to that of girls, R will compute all sums simultaneously.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">arbuthnot<span class="op">$</span>boys <span class="op">+</span><span class="st"> </span>arbuthnot<span class="op">$</span>girls</code></pre></div>
<pre><code>##  [1]  9901  9315  8524  9584  9997  9855 10034  9522  9160 10311 10150
## [12] 10850 10670 10370  9410  8104  7966  7163  7332  6544  5825  5612
## [23]  6071  6128  6155  6620  7004  7050  6685  6170  5990  6971  8855
## [34] 10019 10292 11722  9972  8997 10938 11633 12335 11997 12510 12563
## [45] 11895 11851 11775 12399 12626 12601 12288 12847 13355 13653 14735
## [56] 14702 14730 14694 14951 14588 14771 15211 15054 14918 15159 13632
## [67] 13976 14861 15829 16052 15363 14639 15616 15687 15448 11851 16145
## [78] 15369 16066 15862 15220 14928</code></pre>
<p>What you will see are 82 numbers (in that packed display, because we aren’t looking at a data frame here), each one representing the sum we’re after. Take a look at a few of them and verify that they are right.</p>
</div>
<div id="adding-a-new-variable-to-the-data-frame" class="section level3">
<h3><span class="header-section-number">0.4.4</span> Adding a new variable to the data frame</h3>
<p>We’ll be using this new vector to generate some plots, so we’ll want to save it as a permanent column in our data frame.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">arbuthnot &lt;-<span class="st"> </span>arbuthnot <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">total =</span> boys <span class="op">+</span><span class="st"> </span>girls)</code></pre></div>
<p>What in the world is going on here? The <code>%&gt;%</code> operator is called the <strong>piping</strong> operator. Basically, it takes the output of the current line and pipes it into the following line of code.</p>
<div id="boxedtext">
<p><strong>A note on piping: </strong> Note that we can read these three lines of code as the following:</p>
<p><em>“Take the <code>arbuthnot</code> dataset and <strong>pipe</strong> it into the <code>mutate</code> function. Using this mutate a new variable called <code>total</code> that is the sum of the variables called <code>boys</code> and <code>girls</code>. Then assign this new resulting dataset to the object called <code>arbuthnot</code>, i.e. overwrite the old <code>arbuthnot</code> dataset with the new one containing the new variable.”</em></p>
<p>This is essentially equivalent to going through each row and adding up the boys and girls counts for that year and recording that value in a new column called total.</p>
</div>
<div id="boxedtext">
<p><strong>Where is the new variable? </strong> When you make changes to variables in your dataset, click on the name of the dataset again to update it in the data viewer.</p>
</div>
<p>You’ll see that there is now a new column called <code>total</code> that has been tacked on to the data frame. The special symbol <code>&lt;-</code> performs an <em>assignment</em>, taking the output of one line of code and saving it into an object in your workspace. In this case, you already have an object called <code>arbuthnot</code>, so this command updates that data set with the new mutated column.</p>
<p>We can make a plot of the total number of baptisms per year with the following command.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> arbuthnot, <span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> total)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>()</code></pre></div>
<p><img src="intro-to-data-prob_files/figure-html/plot-total-vs-year-line-1.png" width="672" /></p>
<p>Note that using <code>geom_line()</code> instead of <code>geom_point()</code> results in a line plot instead of a scatter plot. You want both? Just layer them on:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> arbuthnot, <span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> total)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>()</code></pre></div>
<p><img src="intro-to-data-prob_files/figure-html/plot-total-vs-year-line-and-point-1.png" width="672" /></p>
<div id="exercise">
<p><strong>Exercise</strong>: Now, generate a plot of the proportion of boys born over time. What do you see?</p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> arbuthnot, <span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> boys<span class="op">/</span>total)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_line</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</code></pre></div>
<p><img src="intro-to-data-prob_files/figure-html/plot-proportion-of-boys-over-time-1.png" width="672" /></p>
<p>Finally, in addition to simple mathematical operators like subtraction and division, you can ask R to make comparisons like greater than, <code>&gt;</code>, less than, <code>&lt;</code>, and equality, <code>==</code>. For example, we can ask if boys outnumber girls in each year with the expression</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">arbuthnot &lt;-<span class="st"> </span>arbuthnot <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">more_boys =</span> boys <span class="op">&gt;</span><span class="st"> </span>girls)</code></pre></div>
<p>This command add a new variable to the <code>arbuthnot</code> data frame containing the values of either <code>TRUE</code> if that year had more boys than girls, or <code>FALSE</code> if that year did not (the answer may surprise you). This variable contains different kind of data than we have considered so far. All other columns in the <code>arbuthnot</code> data frame have values are numerical (the year, the number of boys and girls). Here, we’ve asked R to create <em>logical</em> data, data where the values are either <code>TRUE</code> or <code>FALSE</code>. In general, data analysis will involve many different kinds of data types, and one reason for using R is that it is able to represent and compute with many of them.</p>
</div>
</div>
<div id="dataset-2-present-birth-records" class="section level2">
<h2><span class="header-section-number">0.5</span> Dataset 2: Present birth records</h2>
<p>In the previous few pages, you recreated some of the displays and preliminary analysis of Arbuthnot’s baptism data. Next you will do a similar analysis, but for present day birth records in the United States. Load up the present day data with the following command.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(present)</code></pre></div>
<p>The data are stored in a data frame called <code>present</code> which should now be loaded in your workspace.</p>
<ol start="4" style="list-style-type: decimal">
<li>How many variables are included in this data set?
<ol>
<li>
2
</li>
<li>
3
</li>
<li>
4
</li>
<li>
74
</li>
<li>
2013
</li>
</ol></li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(present)</code></pre></div>
<pre><code>## [1] 74  3</code></pre>
<div id="exercise">
<p><strong>Exercise</strong>: What years are included in this dataset? <strong>Hint:</strong> Use the <code>range</code> function and <code>present$year</code> as its argument.</p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">range</span>(present<span class="op">$</span>year)</code></pre></div>
<pre><code>## [1] 1940 2013</code></pre>
<ol start="5" style="list-style-type: decimal">
<li>Calculate the total number of births for each year and store these values in a new variable called <code>total</code> in the <code>present</code> dataset. Then, calculate the proportion of boys born each year and store these values in a new variable called <code>prop_boys</code> in the same dataset. Plot these values over time and based on the plot determine if the following statement is true or false: The proportion of boys born in the US has decreased over time.
<ol>
<li>
True
</li>
<li>
False
</li>
</ol></li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># type your code for Question 5 here, and Knit</span>
present &lt;-<span class="st"> </span>present <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">total =</span> boys <span class="op">+</span><span class="st"> </span>girls)
present &lt;-<span class="st"> </span>present <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">prop_boys =</span> (boys<span class="op">/</span>total))
<span class="kw">ggplot</span>(<span class="dt">data =</span> present, <span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> prop_boys)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_line</span>()</code></pre></div>
<p><img src="intro-to-data-prob_files/figure-html/prop-boys-over-time-1.png" width="672" /></p>
<ol start="6" style="list-style-type: decimal">
<li>Create a new variable called <code>more_boys</code> which contains the value of either <code>TRUE</code> if that year had more boys than girls, or <code>FALSE</code> if that year did not. Based on this variable which of the following statements is true?
<ol>
<li>
Every year there are more girls born than boys.
</li>
<li>
Every year there are more boys born than girls.
</li>
<li>
Half of the years there are more boys born, and the other half more girls born.
</li>
</ol></li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># type your code for Question 6 here, and Knit</span>
present &lt;-<span class="st"> </span>present <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">more_boys =</span> boys <span class="op">&gt;</span><span class="st"> </span>girls)</code></pre></div>
<ol start="7" style="list-style-type: decimal">
<li>Calculate the boy-to-girl ratio each year, and store these values in a new variable called <code>prop_boy_girl</code> in the <code>present</code> dataset. Plot these values over time. Which of the following best describes the trend?
<ol>
<li>
There appears to be no trend in the boy-to-girl ratio from 1940 to 2013.
</li>
<li>
There is initially an increase in boy-to-girl ratio, which peaks around 1960. After 1960 there is a decrease in the boy-to-girl ratio, but the number begins to increase in the mid 1970s.
</li>
<li>
There is initially a decrease in the boy-to-girl ratio, and then an increase between 1960 and 1970, followed by a decrease.
</li>
<li>
The boy-to-girl ratio has increased over time.
</li>
<li>
There is an initial decrease in the boy-to-girl ratio born but this number appears to level around 1960 and remain constant since then.
</li>
</ol></li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># type your code for Question 7 here, and Knit</span>
present &lt;-<span class="st"> </span>present <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">prop_boy_girl =</span> boys<span class="op">/</span>girls)
<span class="kw">ggplot</span>(<span class="dt">data =</span> present, <span class="kw">aes</span> (<span class="dt">x =</span> year, <span class="dt">y =</span> prop_boy_girl)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</code></pre></div>
<p><img src="intro-to-data-prob_files/figure-html/prop-boy-girl-over-time-1.png" width="672" /></p>
<ol start="8" style="list-style-type: decimal">
<li>In what year did we see the most total number of births in the U.S.? <em>Hint:</em> Sort your dataset in descending order based on the <code>total</code> column. You can do this interactively in the data viewer by clicking on the arrows next to the variable names. Or to arrange the data in a descenting order with new function: <code>descr</code> (for descending order).
<ol>
<li>
1940
</li>
<li>
1957
</li>
<li>
1961
</li>
<li>
1991
</li>
<li>
2007
</li>
</ol></li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># type your code for Question 8 here</span>
<span class="co"># sample code is provided below, edit as necessary, uncomment, and then Knit</span>
present <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">total =</span> boys <span class="op">+</span>girls) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(total))</code></pre></div>
<pre><code>## # A tibble: 74 x 7
##     year    boys   girls   total prop_boys more_boys prop_boy_girl
##    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt; &lt;lgl&gt;             &lt;dbl&gt;
##  1  2007 2208071 2108162 4316233     0.512 TRUE               1.05
##  2  1961 2186274 2082052 4268326     0.512 TRUE               1.05
##  3  2006 2184237 2081318 4265555     0.512 TRUE               1.05
##  4  1960 2179708 2078142 4257850     0.512 TRUE               1.05
##  5  1957 2179960 2074824 4254784     0.512 TRUE               1.05
##  6  2008 2173625 2074069 4247694     0.512 TRUE               1.05
##  7  1959 2173638 2071158 4244796     0.512 TRUE               1.05
##  8  1958 2152546 2051266 4203812     0.512 TRUE               1.05
##  9  1962 2132466 2034896 4167362     0.512 TRUE               1.05
## 10  1956 2133588 2029502 4163090     0.513 TRUE               1.05
## # ... with 64 more rows</code></pre>
</div>
<div id="resources-for-learning-r-and-working-in-rstudio" class="section level2">
<h2><span class="header-section-number">0.6</span> Resources for learning R and working in RStudio</h2>
<p>That was a short introduction to R and RStudio, but we will provide you with more functions and a more complete sense of the language as the course progresses. You might find the following tips and resources helpful.</p>
<ul>
<li><p>In this course we will be using the <code>dplyr</code> (for data wrangling) and <code>ggplot2</code> (for data visualization) extensively. If you are googling for R code, make sure to also include these package names in your search query. For example, instead of googling “scatterplot in R”, google “scatterplot in R with ggplot2”.</p></li>
<li>The following cheathseets may come in handy throughout the course. Note that some of the code on these cheatsheets may be too advanced for this course, however majority of it will become useful as you progress through the course material.
<ul>
<li><a href="http://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf">Data wrangling cheatsheet</a></li>
<li><a href="http://www.rstudio.com/wp-content/uploads/2015/12/ggplot2-cheatsheet-2.0.pdf">Data visualization cheatsheet</a></li>
<li><a href="http://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf">R Markdown</a></li>
</ul></li>
<li><p>While you will get plenty of exercise working with these packages in the labs of this course, if you would like further opportunities to practice we recommend checking out the relevant courses at <a href="https://www.datacamp.com/courses">DataCamp</a>.</p></li>
</ul>
<div id="license">
<p>This is a derivative of an <a href="https://www.openintro.org/stat/labs.php">OpenIntro</a> lab, and is released under a <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/us/">Attribution-NonCommercial-ShareAlike 3.0 United States</a> license.</p>
</div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="week-2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/01_intro_to_r_Coursera.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["intro-to-data-prob.pdf", "intro-to-data-prob.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
